export const AppConfig = {
  API_BASE_PATH: "api",
  MIN_PASSWORD_LENGTH: 6,
  USERNAME_ALLOWED_PATTERN: /^[a-zA-Z0-9 ]+$/,
  SHORT_FIELD_MAX_LENGTH: 64,
  LONG_FIELD_MAX_LENGTH: 256,
  MIN_LOADING_TIME_MS: 800
}
